# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('signing_date', models.DateField(verbose_name='\u7b7e\u8ba2\u65e5\u671f')),
                ('due_date', models.DateField(verbose_name='\u5b8c\u6210\u65e5\u671f')),
                ('value', models.DateField(verbose_name='\u5408\u540c\u989d')),
            ],
        ),
    ]
