# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.IntegerField(verbose_name='\u5408\u540c\u989d'),
        ),
    ]
