# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0003_contract_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='\u5e74\u5ea6')),
                ('signing_time', models.DateField(verbose_name='\u7b7e\u8ba2\u65e5\u671f')),
                ('due_time', models.DateField(verbose_name='\u5b8c\u6210\u65e5\u671f')),
                ('company', models.CharField(max_length=42, verbose_name='\u7b7e\u8ba2\u65b9')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='\u7f16\u53f7')),
                ('name', models.CharField(max_length=200, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('type', models.CharField(choices=[('C', '\u5e02\u573a'), ('N', '\u56fd\u6295'), ('P', '\u7701\u6295'), ('A', '\u4e0b\u8fbe')], max_length=2, verbose_name='\u9879\u76ee\u7c7b\u578b')),
                ('start_date', models.DateField(verbose_name='\u7b7e\u8ba2\u65e5\u671f')),
                ('due_date', models.DateField(verbose_name='\u5b8c\u6210\u65e5\u671f')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='\u72b6\u6001')),
                ('value', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='\u5408\u540c\u91d1\u989d')),
            ],
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.AddField(
            model_name='income',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swift.Project'),
        ),
    ]
