# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0005_auto_20160809_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='swift.Project'),
        ),
    ]
