# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swift', '0007_auto_20160809_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='description',
            field=models.CharField(default=0, max_length=200, verbose_name='\u8be6\u7ec6\u4fe1\u606f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='other',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='income',
            name='planned',
            field=models.CharField(choices=[('Y', '\u662f'), ('N', '\u5426')], default=datetime.datetime(2016, 8, 9, 9, 0, 48, 584350, tzinfo=utc), max_length=2, verbose_name='\u662f\u5426\u8ba1\u5212\u9879\u76ee'),
            preserve_default=False,
        ),
    ]
